### ISSUE TITLE
main process exits before process pool finishes its tasks. join needed.

### ISSUE THREAD

**Issue by ozgur** [ozgur/python-firebase#5]

**Comment by stevejalim** [comment]
Has this def been addressed? Am getting an OSError when completing a test run invoked through a Fabric script:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/vagrant/.virtualenvs/myproject/local/lib/python2.7/site-packages/firebase/__init__.py", line 13, in close_process_pool
    process_pool.close()
  File "/home/vagrant/.virtualenvs/myproject/local/lib/python2.7/site-packages/firebase/lazy.py", line 10, in __getattribute__
    return getattr(object.__getattribute__(self, "_obj_fn")(), name)
  File "/home/vagrant/.virtualenvs/myproject/local/lib/python2.7/site-packages/firebase/async.py", line 11, in get_process_pool
    _process_pool = multiprocessing.Pool(processes=size)
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 159, in __init__
    self._repopulate_pool()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 223, in _repopulate_pool
    w.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 121, in __init__
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```
